name: Start Redis Server with latest version

on: [push, pull_request]

jobs:
  redis-action:
    runs-on: ubuntu-latest

    name: Start Redis Server with latest Redis version
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Redis Server
        uses: ./
        with:
          redis-version: ${{ matrix.redis-versions }}
